"""
Django settings for bookmarks project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=)tvd@+ns7g$1jitzd3u=r5y+rs3%10a675&kpj73!7uq_d=#v'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['equipo4.org','localhost','127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'account.apps.AccountConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'social_django',
    'django_extensions',
    


]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'bookmarks.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bookmarks.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR,'media/')
STATIC_URL = '/static/'

LOGIN_REDIRECT_URL = 'dashboard'
LOGIN_URL = 'login'
LOGOUT_URL = 'logout'


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'yoni200108@gmail.com'
EMAIL_HOST_PASSWORD = 'cneiowpqjubjjbxw'
EMAIL_USE_TLS = True
#contra por si se me olvida admon = se me olvido jaja

AUTHENTICATION_BACKENDS=['django.contrib.auth.backends.ModelBackend',
                         'account.authentication.EmailAuthBackend',
                         'social_core.backends.facebook.FacebookOAuth2',
                        'social_core.backends.google.GoogleOAuth2',
                        'social_core.backends.spotify.SpotifyOAuth2',
                        #'social_core.backends.twitter.TwitterOAuth',
                        #'social_core.backends.open_id.OpenIdAuth',
                        #'social_core.backends.yahoo.YahooOAuth2',
                        #'social_core.backends.google.GoogleOpenId',
                        #'social_core.backends.github.GithubOAuth2',
			 ]

SOCIAL_AUTH_FACEBOOK_KEY = '746721297123972'
SOCIAL_AUTH_FACEBOOK_SECRET = '5401bb46a05547250a5a31d2e81c9915'

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '382662554619-4gdcf34lk7oblqk27abufq1bfe5bbh1a.apps.googleusercontent.com'
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = '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'

SOCIAL_AUTH_SPOTIFY_KEY = '285a9e0f0c534b6b99d83df7e5d92bfc'
SOCIAL_AUTH_SPOTIFY_SECRET = 'ba7830a833334073815e02764a8e3e4a'
# SOCIAL_AUTH_SPOTIFY_REDIRECT_URI = 'https://127.0.0.1:8000/complete/spotify/'


# SOCIAL_AUTH_TWITTER_KEY = 'aWtjWUdZNWpHYW4zTU5CVFUzNGc6MTpjaQ'
# SOCIAL_AUTH_TWITTER_SECRET = 'EjJid77WH30JGL3dKpi-3m2R4o1WJ0AZWgfKVY5ZDqE2aK6NHC'

# SOCIAL_AUTH_YAHOO_OAUTH2_KEY = 'dj0yJmk9M2Fwa1hkMHNzejlSJmQ9WVdrOWNFbzBabWhZYUdnbWNHbzlNQT09JnM9Y29uc3VtZXJzZWNyZXQmc3Y9MCZ4PTNk'
# SOCIAL_AUTH_YAHOO_OAUTH2_SECRET = '0d70b9e08f6609f3c56c4f4be52d5f3ab48cbcda'

#SOCIAL_AUTH_GITHUB_KEY = '9ad890a662ae9bc1af91'
#SOCIAL_AUTH_GITHUB_SECRET = 'e036f1a87cdd22639d807e2e74e76a415979ad28'
#SOCIAL_AUTH_GITHUB_REDIRECT_URI = 'https://127.0.0.1:8000/complete/github/'

#1674171650-DaS2mFOGi1Guz81cJ96lCkkL2GlHJcR7bdp8Nk5
#LODtRDaZtCalfOrcPZnEthtulxYrn46ym9pMSX2sRpfd2